program: run.py

project: lightning-hydra-template

description: "Fashion MNIST wandb sweep"

method: bayes

metric:
  name: val/acc
  goal: maximize

parameters:
  model.optimizer.lr:
    distribution: uniform
    min: 0.0001
    max: 0.1
  model.net.conv_channels:
    values: [32, 64, 128, 256, 512]
  model.net.fc_channels:
    values: [32, 64, 128, 256, 512]
  data.batch_size:
    values: [32, 64, 128]

early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 16

command:
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
  - logger=wandb