_target_: src.models.lit_module.FashionMNISTLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.cnn.CNN
  conv_channels: [1, 16, 32, 64]
  kernel_size: 5
  stride: 1
  use_batch_norm: True
  fc_channels: [10]
