_target_: src.models.lit_module.FashionMNISTLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.cnn.CNN
  input_shape: (1, 28, 28)
  n_conv_layers: 3
  kernel_size: 5
  batch_norm: False
  global_avg_pooling: True,
  in_channels: 1,
  key_conv: n_channels_conv_
  key_fc: n_channels_fc_
  out_channels: 16
  dropout_rate: 0.2
  n_fc_layers: 3
  num_classes: 10
