_target_: src.models.lit_module.FashionMNISTLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.mlp.MLP
  input_size: 784
  lin1_size: 64 # 128
  lin2_size: 128 # 256
  lin3_size: 64
  output_size: 10
